### ISSUE TITLE
Requesting Left Taskbar

### ISSUE THREAD

**Issue by MarioAtTrimble** [jetspiking/Taskbar11#10]
I have used left taskbar on my main monitor, and a bottom taskbar on my other monitors for years.  Could you add functionality to accomplish this?

**Comment by mtrtm** [comment]
https://techcommunity.microsoft.com/t5/report-an-issue/taskbar-location-not-configurable/m-p/2948422

**Comment by jetspiking** [comment]
Hi! Unfortunately editing the corresponding registry values for a left or right taskbar results in an unusable taskbar. This application works by only editing or creating registry values.  Due to this reason this feature can not be implemented. I am hoping the taskbar will be revised in a future Windows 11 update, to solve most issues with it.

You could choose to set the taskbar to the bottom or top with small icon sizes, you will atleast get a little screen space back this way.

**Comment by MarioAtTrimble** [comment]
well shucks.  Thanks for the reply
