### ISSUE TITLE
Applying new settings broke TranslucentTB

### ISSUE THREAD

**Issue by ivan70f** [jetspiking/Taskbar11#19]
When I applyed new settings in ur app TranscluentTB crashed. Now, when I start TranscluentTB taskbar became black. Restarting didn't help.

**Comment by jetspiking** [comment]
Hi! Thank you for opening the issue. Taskbar11 modifies existing registry values, since the latest version "Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" is being modified. Does this key exist on your system? If not re-creating it might help. Another option is to check / uncheck the option "Use Old Context Menu For Right Mouse Button Click". Afterwards you could run TranslucentTB again to verify whether this issue is still present.
