### ISSUE TITLE
Taskbar Position - Left/Right

### ISSUE THREAD

**Issue by Erikdc666** [jetspiking/Taskbar11#27]
I just updated to Windows 11, but I used to have my taskbar snapped sideways, to the left of my screen.

Now I see only top/bottom options in your app, is there any chance you still plan to implement that?

Thanks!

**Comment by jetspiking** [comment]
Hi there! At the moment there is only support for a bottom or top aligned taskbar due to registry edit implementation. However, this also has been removed by Microsoft in Windows Dev Version 22533 and higher. I hope a solution is possible for this by directly manipulating the Window classes, I still need to examine this. 

There are a few alternatives which do support sideways taskbars at the moment. You could take a look at Explorer Patcher on GitHub, this might be a better solution for you.
