### ISSUE TITLE
This app causes another app to crash (TranslucentTB)

### ISSUE THREAD

**Issue by ejuarbe** [jetspiking/Taskbar11#29]
When applying the settings in this app, TransclucentTB will shut down with an error.  Translucent TB is able to start again, but during this time, the taskbar background color becomes clear.

**Comment by ejuarbe** [comment]
I found one more bigger bug:

1. When the taskbar is set to Top, If you open the Internet and Sound tray flyout, the menu frame/ocntainer is shifted down, while buttons and options inside the container are in their 'standard' place, making the upper buttons cut off of the upper container edge.

Here's an example:

![Sample cut container](https://user-images.githubusercontent.com/5740075/152622087-7d7af057-fe52-4da2-951e-3a17f369c228.png)

**Comment by jetspiking** [comment]
Hi there! 

Since the application works by adjusting registry values, some bugs are present and can not be fixed at the moment. Reverting the settings to the defaults as described here should eliminate all bugs. However, that means you can not use the top aligned taskbar.

https://github.com/jetspiking/Taskbar11/issues/24
