### ISSUE TITLE
Taskbar on left  side...

### ISSUE THREAD

**Issue by MatthiasMunich** [jetspiking/Taskbar11#33]
Hi jetspiking, 

would appreciate so much if taskbar could be aligned to left side. Frankly  - I hate taskbar on top or bottom, have been using it on left side of screen since Win XP and would never want to miss that feature. For me the main reason currently NOT to upgrade from Win 10 to 11. So stupid what MS did here ...

![image](https://user-images.githubusercontent.com/99738212/154075397-4448f19a-cc03-459a-a1f2-547e0814f2f1.png)
.... can this maybe help in establishing this feature into your App?
Thank you

Best greetings from Munich
Matt

**Comment by jetspiking** [comment]
Hi Matt,

Sorry for the late reply!

Unfortunately this registry edit does not work correctly in Windows 11. It will result in a broken unusable taskbar. Because of this these hex values 00 and 02 are not included in Taskbar11. 

The only solution for this is to use an alternative to Taskbar11, that entirely rebuilds the Taskbar instead of modifying it by Registry Tweaks.

Kind regards,

Dustin
