### ISSUE TITLE
Allow taskbar to be moved left & right

### ISSUE THREAD

**Issue by aldeniangman** [jetspiking/Taskbar11#36]
Hi,
_So many people want to_ have the taskbar **Left and right** **EVEN ME!**
### Check list

- [ ] Allow right
- [ ] Allow left

**Comment by jetspiking** [comment]
Hi,

Sorry for the late reply!

This application works by adjusting registry values to represent the taskbar position. Unfortunately this registry edit does not work correctly in Windows 11 for a left or right aligned taskbar. It will result in a broken unusable taskbar.

The only solution for this is to use an alternative to Taskbar11, that entirely rebuilds the Taskbar instead of modifying it by Registry Tweaks.

Kind regards,

Dustin
